In [13]:
#import libraries
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import tree


In [14]:
#read dataset
dataset = pd.read_csv('weather.csv')
dataset

Unnamed: 0   Outlook Temperature Humidity  Windy Play golf
0            0     Rainy         Hot     High  False        No
1            1     Rainy         Hot     High   True        No
2            2  Overcast         Hot     High  False       Yes
3            3     Sunny        Mild     High  False       Yes
4            4     Sunny        Cool   Normal  False       Yes
5            5     Sunny        Cool   Normal   True        No
6            6  Overcast        Cool   Normal   True       Yes
7            7     Rainy        Mild     High  False        No
8            8     Rainy        Cool   Normal  False       Yes
9            9     Sunny        Mild   Normal  False       Yes
10          10     Rainy        Mild   Normal   True       Yes
11          11  Overcast        Mild     High   True       Yes
12          12  Overcast         Hot   Normal  False       Yes
13          13     Sunny        Mild     High   True        No

In [15]:
#preprocessing
dataset = pd.DataFrame(data=dataset.iloc[:,1:6].values,columns=["outlook","temperature","humidity","windy","play"])

In [16]:
dataset

outlook temperature humidity  windy play
0      Rainy         Hot     High  False   No
1      Rainy         Hot     High   True   No
2   Overcast         Hot     High  False  Yes
3      Sunny        Mild     High  False  Yes
4      Sunny        Cool   Normal  False  Yes
5      Sunny        Cool   Normal   True   No
6   Overcast        Cool   Normal   True  Yes
7      Rainy        Mild     High  False   No
8      Rainy        Cool   Normal  False  Yes
9      Sunny        Mild   Normal  False  Yes
10     Rainy        Mild   Normal   True  Yes
11  Overcast        Mild     High   True  Yes
12  Overcast         Hot   Normal  False  Yes
13     Sunny        Mild     High   True   No

In [17]:
#LabelEncoder will convert categorical values to numerical values
le = LabelEncoder()
dataset_encoded = dataset.iloc[:,0:5]# 0th cloumn to 4th cloumn

#le=fit_transform(dataset_encoded['outlook'])#taking one encoded output
#convert all columns data to encoded values
for i in dataset_encoded:
    dataset_encoded[i] = le.fit_transform(dataset_encoded[i])

In [18]:
print(dataset_encoded)
print(dataset)

    outlook  temperature  humidity  windy  play
0         1            1         0      0     0
1         1            1         0      1     0
2         0            1         0      0     1
3         2            2         0      0     1
4         2            0         1      0     1
5         2            0         1      1     0
6         0            0         1      1     1
7         1            2         0      0     0
8         1            0         1      0     1
9         2            2         1      0     1
10        1            2         1      1     1
11        0            2         0      1     1
12        0            1         1      0     1
13        2            2         0      1     0
     outlook temperature humidity  windy play
0      Rainy         Hot     High  False   No
1      Rainy         Hot     High   True   No
2   Overcast         Hot     High  False  Yes
3      Sunny        Mild     High  False  Yes
4      Sunny        Cool   Normal  False  Yes
5   

In [20]:
#set feature names into variables
column_names = dataset_encoded.iloc[:,0:4].columns
column_names

Index(['outlook', 'temperature', 'humidity', 'windy'], dtype='object')

In [21]:
#columns used to make predictions
X = dataset_encoded.iloc[:,0:4].values
X

array([[1, 1, 0, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 0],
       [2, 2, 0, 0],
       [2, 0, 1, 0],
       [2, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 2, 0, 0],
       [1, 0, 1, 0],
       [2, 2, 1, 0],
       [1, 2, 1, 1],
       [0, 2, 0, 1],
       [0, 1, 1, 0],
       [2, 2, 0, 1]])

In [22]:
#predictive attribute
Y = dataset_encoded.iloc[:,4].values
Y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [24]:
#split dataset into train set and test set
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=1,random_state=100)

In [25]:
X_train

array([[0, 1, 1, 0],
       [2, 0, 1, 1],
       [1, 1, 0, 1],
       [2, 2, 1, 0],
       [2, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [1, 1, 0, 0],
       [1, 2, 1, 1],
       [1, 2, 0, 0],
       [2, 2, 0, 0],
       [2, 2, 0, 1],
       [1, 0, 1, 0]])

In [26]:
X_test

array([[0, 2, 0, 1]])

In [27]:
y_train

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1])

In [28]:
y_test

array([1])

In [29]:
#create decision tree and fit it into train data set
model = DecisionTreeClassifier(criterion='gini',max_depth=5)

In [30]:
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [32]:
#prediction
model.predict([(0,0,0,0)])

array([1])

In [34]:
model.predict([(0,1,0,0)])

array([1])

In [36]:
#calculating the accuracy
model.score(X_test,y_test)

1.0

In [39]:
#visualizing decision treee
from sklearn import tree
tree.export_graphviz(model, out_file='play-golf.dot',
                    feature_names=column_names,
                    class_names = ['Yes','No'],
                     label='all',
                     rounded=True,
                     filled=True,
                    special_characters=True)